controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    arm_joints_controller:
      type: forward_command_controller/ForwardCommandController

    my_arm_joints_controller:
      type: complimentary_filter_controller/ComplimentaryFilterController

diff_drive_controller:
  ros__parameters: # adding para for node we created
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    
    wheel_separation: 0.45
    wheel_radius: 0.1

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true
    publish_rate: 50.0

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

arm_joints_controller:
  ros__parameters:
    joints: ["arm_base_forearm_joint", "forearm_hand_joint"]
    interface_name: "position"

my_arm_joints_controller:
  ros__parameters:
    joints: ["arm_base_forearm_joint", "forearm_hand_joint"]
    interface_name: "position"
    coefficient: 0.05